version: '3.8'

volumes:
  postgre_vol:

networks:
  postgre_net:
    driver: bridge

services:
  pgadmin:
    image: dpage/pgadmin4:6.20
    networks:
      - postgre_net
    depends_on:
      - postgre
    environment:
      PGADMIN_DEFAULT_EMAIL: deividfae@yahoo.com.br
      PGADMIN_DEFAULT_PASSWORD: pgadminpwd
      PGADMIN_LISTEN_PORT: 80
      POSTGRES_PASSWORD: postgrepwd
      POSTGRES_USER: postgreuser
      POSTGRES_DB: postgredb
    ports:
      - 8082:80

  postgre:
    image: postgres:15.2
    networks:
      - postgre_net
    volumes:
      - postgre_vol:/data/db
    environment:
      POSTGRES_PASSWORD: postgrepwd
      POSTGRES_USER: postgreuser
      POSTGRES_DB: postgredb    